package org.njqspringboot.model.member;

import java.io.Serializable;
import java.util.Date;

public class MemberInfo implements Serializable{
	private static final long serialVersionUID = 6452798508918506695L;
	
	
	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xx_member.id
     *
     * @mbggenerated Sat Jul 30 10:34:39 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xx_member.store_id
     *
     * @mbggenerated Sat Jul 30 10:34:39 CST 2016
     */
    private Long storeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xx_member.username
     *
     * @mbggenerated Sat Jul 30 10:34:39 CST 2016
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xx_member.password
     *
     * @mbggenerated Sat Jul 30 10:34:39 CST 2016
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xx_member.sex
     *
     * @mbggenerated Sat Jul 30 10:34:39 CST 2016
     */
    private Short sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xx_member.id_card_no
     *
     * @mbggenerated Sat Jul 30 10:34:39 CST 2016
     */
    private String idCardNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xx_member.age
     *
     * @mbggenerated Sat Jul 30 10:34:39 CST 2016
     */
    private Integer age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xx_member.usertype
     *
     * @mbggenerated Sat Jul 30 10:34:39 CST 2016
     */
    private Short usertype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xx_member.enabled
     *
     * @mbggenerated Sat Jul 30 10:34:39 CST 2016
     */
    private Integer enabled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xx_member.realname
     *
     * @mbggenerated Sat Jul 30 10:34:39 CST 2016
     */
    private String realname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xx_member.address
     *
     * @mbggenerated Sat Jul 30 10:34:39 CST 2016
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xx_member.fieldsfact
     *
     * @mbggenerated Sat Jul 30 10:34:39 CST 2016
     */
    private String fieldsfact;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xx_member.fields
     *
     * @mbggenerated Sat Jul 30 10:34:39 CST 2016
     */
    private String fields;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xx_member.phone_number
     *
     * @mbggenerated Sat Jul 30 10:34:39 CST 2016
     */
    private String phoneNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xx_member.members
     *
     * @mbggenerated Sat Jul 30 10:34:39 CST 2016
     */
    private Integer members;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xx_member.crop
     *
     * @mbggenerated Sat Jul 30 10:34:39 CST 2016
     */
    private String crop;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xx_member.vip_card
     *
     * @mbggenerated Sat Jul 30 10:34:39 CST 2016
     */
    private String vipCard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xx_member.create_time
     *
     * @mbggenerated Sat Jul 30 10:34:39 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xx_member.create_user
     *
     * @mbggenerated Sat Jul 30 10:34:39 CST 2016
     */
    private Integer createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xx_member.update_time
     *
     * @mbggenerated Sat Jul 30 10:34:39 CST 2016
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xx_member.member_desc
     *
     * @mbggenerated Sat Jul 30 10:34:39 CST 2016
     */
    private String memberDesc;


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xx_member.id
     *
     * @return the value of xx_member.id
     *
     * @mbggenerated Sat Jul 30 10:34:39 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xx_member.id
     *
     * @param id the value for xx_member.id
     *
     * @mbggenerated Sat Jul 30 10:34:39 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xx_member.store_id
     *
     * @return the value of xx_member.store_id
     *
     * @mbggenerated Sat Jul 30 10:34:39 CST 2016
     */
    public Long getStoreId() {
        return storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xx_member.store_id
     *
     * @param storeId the value for xx_member.store_id
     *
     * @mbggenerated Sat Jul 30 10:34:39 CST 2016
     */
    public void setStoreId(Long storeId) {
        this.storeId = storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xx_member.username
     *
     * @return the value of xx_member.username
     *
     * @mbggenerated Sat Jul 30 10:34:39 CST 2016
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xx_member.username
     *
     * @param username the value for xx_member.username
     *
     * @mbggenerated Sat Jul 30 10:34:39 CST 2016
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xx_member.password
     *
     * @return the value of xx_member.password
     *
     * @mbggenerated Sat Jul 30 10:34:39 CST 2016
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xx_member.password
     *
     * @param password the value for xx_member.password
     *
     * @mbggenerated Sat Jul 30 10:34:39 CST 2016
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xx_member.sex
     *
     * @return the value of xx_member.sex
     *
     * @mbggenerated Sat Jul 30 10:34:39 CST 2016
     */
    public Short getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xx_member.sex
     *
     * @param sex the value for xx_member.sex
     *
     * @mbggenerated Sat Jul 30 10:34:39 CST 2016
     */
    public void setSex(Short sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xx_member.id_card_no
     *
     * @return the value of xx_member.id_card_no
     *
     * @mbggenerated Sat Jul 30 10:34:39 CST 2016
     */
    public String getIdCardNo() {
        return idCardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xx_member.id_card_no
     *
     * @param idCardNo the value for xx_member.id_card_no
     *
     * @mbggenerated Sat Jul 30 10:34:39 CST 2016
     */
    public void setIdCardNo(String idCardNo) {
        this.idCardNo = idCardNo == null ? null : idCardNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xx_member.age
     *
     * @return the value of xx_member.age
     *
     * @mbggenerated Sat Jul 30 10:34:39 CST 2016
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xx_member.age
     *
     * @param age the value for xx_member.age
     *
     * @mbggenerated Sat Jul 30 10:34:39 CST 2016
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xx_member.usertype
     *
     * @return the value of xx_member.usertype
     *
     * @mbggenerated Sat Jul 30 10:34:39 CST 2016
     */
    public Short getUsertype() {
        return usertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xx_member.usertype
     *
     * @param usertype the value for xx_member.usertype
     *
     * @mbggenerated Sat Jul 30 10:34:39 CST 2016
     */
    public void setUsertype(Short usertype) {
        this.usertype = usertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xx_member.enabled
     *
     * @return the value of xx_member.enabled
     *
     * @mbggenerated Sat Jul 30 10:34:39 CST 2016
     */
    public Integer getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xx_member.enabled
     *
     * @param enabled the value for xx_member.enabled
     *
     * @mbggenerated Sat Jul 30 10:34:39 CST 2016
     */
    public void setEnabled(Integer enabled) {
        this.enabled = enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xx_member.realname
     *
     * @return the value of xx_member.realname
     *
     * @mbggenerated Sat Jul 30 10:34:39 CST 2016
     */
    public String getRealname() {
        return realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xx_member.realname
     *
     * @param realname the value for xx_member.realname
     *
     * @mbggenerated Sat Jul 30 10:34:39 CST 2016
     */
    public void setRealname(String realname) {
        this.realname = realname == null ? null : realname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xx_member.address
     *
     * @return the value of xx_member.address
     *
     * @mbggenerated Sat Jul 30 10:34:39 CST 2016
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xx_member.address
     *
     * @param address the value for xx_member.address
     *
     * @mbggenerated Sat Jul 30 10:34:39 CST 2016
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xx_member.fieldsfact
     *
     * @return the value of xx_member.fieldsfact
     *
     * @mbggenerated Sat Jul 30 10:34:39 CST 2016
     */
    public String getFieldsfact() {
        return fieldsfact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xx_member.fieldsfact
     *
     * @param fieldsfact the value for xx_member.fieldsfact
     *
     * @mbggenerated Sat Jul 30 10:34:39 CST 2016
     */
    public void setFieldsfact(String fieldsfact) {
        this.fieldsfact = fieldsfact == null ? null : fieldsfact.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xx_member.fields
     *
     * @return the value of xx_member.fields
     *
     * @mbggenerated Sat Jul 30 10:34:39 CST 2016
     */
    public String getFields() {
        return fields;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xx_member.fields
     *
     * @param fields the value for xx_member.fields
     *
     * @mbggenerated Sat Jul 30 10:34:39 CST 2016
     */
    public void setFields(String fields) {
        this.fields = fields == null ? null : fields.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xx_member.phone_number
     *
     * @return the value of xx_member.phone_number
     *
     * @mbggenerated Sat Jul 30 10:34:39 CST 2016
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xx_member.phone_number
     *
     * @param phoneNumber the value for xx_member.phone_number
     *
     * @mbggenerated Sat Jul 30 10:34:39 CST 2016
     */
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber == null ? null : phoneNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xx_member.members
     *
     * @return the value of xx_member.members
     *
     * @mbggenerated Sat Jul 30 10:34:39 CST 2016
     */
    public Integer getMembers() {
        return members;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xx_member.members
     *
     * @param members the value for xx_member.members
     *
     * @mbggenerated Sat Jul 30 10:34:39 CST 2016
     */
    public void setMembers(Integer members) {
        this.members = members;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xx_member.crop
     *
     * @return the value of xx_member.crop
     *
     * @mbggenerated Sat Jul 30 10:34:39 CST 2016
     */
    public String getCrop() {
        return crop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xx_member.crop
     *
     * @param crop the value for xx_member.crop
     *
     * @mbggenerated Sat Jul 30 10:34:39 CST 2016
     */
    public void setCrop(String crop) {
        this.crop = crop == null ? null : crop.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xx_member.vip_card
     *
     * @return the value of xx_member.vip_card
     *
     * @mbggenerated Sat Jul 30 10:34:39 CST 2016
     */
    public String getVipCard() {
        return vipCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xx_member.vip_card
     *
     * @param vipCard the value for xx_member.vip_card
     *
     * @mbggenerated Sat Jul 30 10:34:39 CST 2016
     */
    public void setVipCard(String vipCard) {
        this.vipCard = vipCard == null ? null : vipCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xx_member.create_time
     *
     * @return the value of xx_member.create_time
     *
     * @mbggenerated Sat Jul 30 10:34:39 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xx_member.create_time
     *
     * @param createTime the value for xx_member.create_time
     *
     * @mbggenerated Sat Jul 30 10:34:39 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xx_member.create_user
     *
     * @return the value of xx_member.create_user
     *
     * @mbggenerated Sat Jul 30 10:34:39 CST 2016
     */
    public Integer getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xx_member.create_user
     *
     * @param createUser the value for xx_member.create_user
     *
     * @mbggenerated Sat Jul 30 10:34:39 CST 2016
     */
    public void setCreateUser(Integer createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xx_member.update_time
     *
     * @return the value of xx_member.update_time
     *
     * @mbggenerated Sat Jul 30 10:34:39 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xx_member.update_time
     *
     * @param updateTime the value for xx_member.update_time
     *
     * @mbggenerated Sat Jul 30 10:34:39 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xx_member.member_desc
     *
     * @return the value of xx_member.member_desc
     *
     * @mbggenerated Sat Jul 30 10:34:39 CST 2016
     */
    public String getMemberDesc() {
        return memberDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xx_member.member_desc
     *
     * @param memberDesc the value for xx_member.member_desc
     *
     * @mbggenerated Sat Jul 30 10:34:39 CST 2016
     */
    public void setMemberDesc(String memberDesc) {
        this.memberDesc = memberDesc == null ? null : memberDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xx_member
     *
     * @mbggenerated Sat Jul 30 10:34:39 CST 2016
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", storeId=").append(storeId);
        sb.append(", username=").append(username);
        sb.append(", password=").append(password);
        sb.append(", sex=").append(sex);
        sb.append(", idCardNo=").append(idCardNo);
        sb.append(", age=").append(age);
        sb.append(", usertype=").append(usertype);
        sb.append(", enabled=").append(enabled);
        sb.append(", realname=").append(realname);
        sb.append(", address=").append(address);
        sb.append(", fieldsfact=").append(fieldsfact);
        sb.append(", fields=").append(fields);
        sb.append(", phoneNumber=").append(phoneNumber);
        sb.append(", members=").append(members);
        sb.append(", crop=").append(crop);
        sb.append(", vipCard=").append(vipCard);
        sb.append(", createTime=").append(createTime);
        sb.append(", createUser=").append(createUser);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", memberDesc=").append(memberDesc);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

}
